FROM mcr.microsoft.com/windows/servercore:1809

# Setting PowerShell as a default executor. 
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN choco --version
